# Copyright (c) 2019 Intel Corporation. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Check if we have required SST-BF information
  fail:
    msg: "Variable {{ required_var }} is not defined"
  with_items:
    - "normal_cores"
    - "high_cores"
  loop_control:
    loop_var: required_var
  when: vars[required_var] is undefined

- name: Setup information
  set_fact:
    high_cores_l: "{{ high_cores.stdout_lines[0].split(',') }}"
    normal_cores_l: "{{ normal_cores.stdout_lines[0].split(',') }}"
    pinned_cores_l: []

- name: Install python3-apt
  command: apt install -y python3-apt
  when: ansible_distribution == 'Ubuntu' and not offline

# Note: igb_uio kernel module needs special compilation from source
#       which is achieved with the package below on Ubuntu 18.04
- name: Setup igb_uio kernel module on Ubuntu 18.04
  block:
    - name: Ensure we have dpdk-igb-uio-dkms installed
      apt:
        name: dpdk-igb-uio-dkms
        state: present

    - name: Ensure we have igb_uio module
      modprobe:
        name: igb_uio
        state: present
  when: ansible_distribution == 'Ubuntu' and
        ansible_distribution_version == '18.04' and
        ovs_dpdk_driver == 'igb_uio' and
        not offline

- name: Get total amount of CPUs to pin
  set_fact:
    total_cpus_pin: "{{ (total_cpus_pin | default(0) | int) + \
                    (numa_id.value.no_physical_cores_pinned | default(0) | int) }}"
  with_dict: "{{ host_description['numa_nodes'] }}"
  loop_control:
    loop_var: numa_id

- name: Ensure we are pinning one or more cores in total
  fail:
    msg: "Please define one or more cores for pinning"
  when: total_cpus_pin | int < 1

# Note: We assume two threads per core here
- name: Fail if there is not enough high cpu resources
  fail:
    msg: "Not enough cpu resources to cover high cpu pinning request"
  when: ovs_core_high_priority and
        total_cpus_pin | int * 2 > high_cores_l | length

- name: Fail if there is not enough normal cpu resources
  fail:
    msg: "Not enough cpu resources to cover normal cpu pinning request"
  when: not ovs_core_high_priority and
        total_cpus_pin | int * 2 > normal_cores_l | length

- name: Get high or normal priority OVS-DPDK PMD core(s) for each NUMA node
  include: get_cores.yml
  vars:
    numa_no: "{{ numa_node.key }}"
    no_cores_pinned: " {{ numa_node.value.no_physical_cores_pinned }}"
    sibling_needed: true
  with_dict: "{{ host_description['numa_nodes'] }}"
  loop_control:
    loop_var: numa_node
  when: numa_node.value.no_physical_cores_pinned > 0

- name: Store list of cores that are pinned
  set_fact:
    ovs_dpdk_pmd_core_l: "{{ pinned_cores_l }}"

- name: Register supporting python script
  stat:
    path: "{{ role_path }}/files/convert_cpu_hex.py"
  register: support_hex_stat

- name: Check for symbolic link attack
  fail:
    msg: "Possible symbolic link attack detected for file at files/convert_cpu_hex.py"
  when: support_hex_stat.stat.exists and support_hex_stat.stat.islnk

- name: Generate hex for pinning OVS-DPDK PMD
  script: "{{ role_path }}/files/convert_cpu_hex.py {{ pinned_cores_l | join(',') }}"
  delegate_to: 127.0.0.1
  register: ovs_dpdk_pmd_mask

- name: Set up to get DPDK lcore mask
  set_fact:
    pinned_cores_l: []

- name: Get a cores siblings to infer no. of threads per physical core
  command: "cat /sys/devices/system/cpu/cpu0/topology/thread_siblings_list"
  register: sample_siblings
  changed_when: true

- name: Set threads (logical cores) per physical core
  set_fact:
    threads_core: "{{ sample_siblings.stdout_lines[0].split(',') | length }}"

- name: Get normal priority core for OVS-DPDK lcore and core siblings
  include: get_cores.yml
  vars:
    numa_no: 0
    no_cores_pinned: "{{ no_ovs_dpdk_lcore_pinned / (threads_core | int) | int }}"
    sibling_needed: true
    ovs_core_high_priority: false
  when: no_ovs_dpdk_lcore_pinned >= (threads_core | int)

- name: Get single normal priority core for OVS-DPDK lcore
  include: get_cores.yml
  vars:
    numa_no: 0
    no_cores_pinned: "{{ no_ovs_dpdk_lcore_pinned % (threads_core | int) }}"
    sibling_needed: false
    ovs_core_high_priority: false
  when: no_ovs_dpdk_lcore_pinned % (threads_core | int) != 0

- name: Generate hex for pinning OVS-DPDK lcore
  script: "{{ role_path }}/files/convert_cpu_hex.py {{ pinned_cores_l | join(',') }}"
  delegate_to: 127.0.0.1
  register: ovs_dpdk_lcore_mask

- name: Ensure required drivers/modules persist after a reboot
  block:
    - name: Register modules file
      stat:
        path: /etc/modules
      register: mod

    - name: Check if modules file exists
      fail:
        msg: "'/etc/modules' file does not exist"
      when: not mod.stat.exists

    - name: Check for symbolic link attack
      fail:
        msg: "Possible symbolic link attack for file '/etc/modules'"
      when: mod.stat.islnk

    - name: Add kernel module to modules file
      lineinfile:
        path: /etc/modules
        line: "{{ ovs_dpdk_driver }}"
        regexp: "^{{ ovs_dpdk_driver }}"
        state: present

    - name: Add OpenvSwitch module to file
      lineinfile:
        path: /etc/modules
        line: 'openvswitch'
        regexp: '^openvswitch'
        state: present
  when: ansible_distribution == 'Ubuntu'

- name: Ensure required drivers/modules persist after a reboot
  block:
    - name: Register modules directory
      stat:
        path: /etc/modules-load.d
      register: mod_l

    - name: Check if modules folder exists
      fail:
        msg: "'/etc/modules-load.d' directory does not exist"
      when: not mod_l.stat.exists

    - name: Check for symbolic link attack
      fail:
        msg: "Possible symbolic link attack for directory '/etc/modules-load.d'"
      when: mod_l.stat.islnk is defined and mod_l.stat.islnk

    - name: Register OVS-DPDK module file
      stat:
        path: /etc/modules-load.d/ovs-dpdk
      register: mod_ovs

    - name: Check for symbolic link attack
      fail:
        msg: "Possible symbolic link attack for file '/etc/modules-load.d/ovs-dpdk'"
      when: mod_ovs.stat.exists and mod_ovs.stat.islnk

    - name: Add OpenvSwitch module to file
      lineinfile:
        path: /etc/modules-load.d/ovs-dpdk
        line: "{{ ovs_dpdk_driver }}"
        regexp: "^{{ ovs_dpdk_driver }}"
        state: present
        create: yes
  when: ansible_distribution != 'Ubuntu'

- name: Register grub file
  stat:
    path: /etc/default/grub
  register: default_grub

- name: Check for symbolic link attack
  fail:
    msg: "Possible symbolic link attack on file '/etc/default/grub'"
  when: default_grub.stat.islnk is defined and default_grub.stat.islnk

- name: Check if GRUB_CMDLINE_LINUX present from GRUB file
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX="
    state: absent
  check_mode: yes
  changed_when: false
  register: grub

- name: Insert GRUB_CMDLINE_LINUX
  lineinfile:
    dest: /etc/default/grub
    line: GRUB_CMDLINE_LINUX=""
  when: not grub.found

- name: Remove GRUB CMD line key-values we are replacing
  replace:
    path: /etc/default/grub
    regexp: "\\s*{{ item }}=[']?[a-zA-Z0-9,-]+[']?"
    replace: ""
  loop:
    - "default_hugepagesz"
    - "hugepagesz"
    - "hugepages"
    - "isolcpus"
    - "intel_iommu"
    - "iommu"

- name: Insert GRUB_CMDLINE_LINUX in GRUB with hugepage & isolcpus
  replace:
    path: /etc/default/grub
    regexp: '(^GRUB_CMDLINE_LINUX=\"(.*)?)(\")'
    replace: '\1 default_hugepagesz=1G hugepagesz=1G
           hugepages={{ ovs_dpdk_nr_1g_pages }} hugepagesz=2M
           hugepages={{ ovs_dpdk_nr_2m_pages }}
           isolcpus={{ ovs_dpdk_pmd_core_l| join(",") }} iommu=pt intel_iommu=on\3'
  when: ansible_distribution == 'Ubuntu' or
        ansible_distribution == 'Fedora' or
        ansible_distribution == 'CentOS' or
        ansible_distribution == 'RedHat'

- name: Update grub
  command: update-grub
  when: ansible_distribution == 'Ubuntu'

- name: Update grub
  shell: grub2-mkconfig -o "$(readlink -e /etc/grub2.conf)"
  when: ansible_distribution != 'Ubuntu'

- name: Reboot
  shell: "sleep 1 && shutdown -r now 'Ansible update to GRUB - forced restart'"
  changed_when: true
  async: 1
  poll: 0

- name: Wait for reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 600

- name: Install OVS-DPDK packages for Ubuntu
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - openvswitch-common
      - openvswitch-switch-dpdk
  when: ansible_distribution == 'Ubuntu' and
        not offline and
        not ovs_dpdk_installed|bool

- name: Configure OpenvSwitch-DPDK and restart service
  block:
    - name: Register OVS-DPDK file
      stat:
        path: /usr/lib/openvswitch-switch-dpdk/ovs-vswitchd-dpdk
      register: ovs_vswitch_dpdk

    - name: Check if ovs-vswitchd-dpdk file exists
      fail:
        msg: "ovs-vswitchd-dpdk file does not exist"
      when: not ovs_vswitch_dpdk.stat.exists

    - name: Check if symbolic link
      fail:
        msg: "Possible symbolic link attack detected"
      when: ovs_vswitch_dpdk.stat.islnk is defined and ovs_vswitch_dpdk.stat.islnk

    - name: Set alternative ovs-vswitchd service
      alternatives:
        name: ovs-vswitchd
        path: /usr/lib/openvswitch-switch-dpdk/ovs-vswitchd-dpdk

    - name: Register DPDK folder
      stat:
        path: "/etc/dpdk"
      register: dpdk_dir

    - name: Check if DPDK directory is symbolically linked
      fail:
        msg: "Possible symbolic link attack detected"
      when: dpdk_dir.stat.islnk is defined and dpdk_dir.stat.islnk

    - name: Check if DPDK folder exists
      fail:
        msg: "'/etc/dpdk' folder does not exist"
      when: not dpdk_dir.stat.exists

    - name: Check if path is a directory
      fail:
        msg: "'/etc/dpdk' is not a directory"
      when: dpdk_dir.stat.isdir is defined and not dpdk_dir.stat.isdir

    - name: Configure DPDK interface for driver bindings
      template:
        src: dpdk_interfaces.j2
        dest: "/etc/dpdk/interfaces"
        owner: "root"
        group: "root"

    - name: Configure DPDK hugepage allocation
      template:
        src: dpdk.conf.j2
        dest: "/etc/dpdk/dpdk.conf"
        owner: "root"
        group: "root"

    - name: Ensure DPDK service is running
      systemd:
        name: dpdk
        state: restarted
        enabled: yes
  when: not ovs_dpdk_installed | bool and not offline

- name: Ensure Open vSwitch is running
  systemd:
    name: "{{ ovs_service_name }}"
    state: restarted
    enabled: yes

- name: Pause for 5 seconds to ensure services have time to come back up
  pause:
    seconds: 5

- name: Set DPDK lcore mask
  command: "ovs-vsctl --no-wait set Open_vSwitch . \
            other_config:dpdk-lcore-mask='{{ ovs_dpdk_lcore_mask.stdout_lines[0] }}'"
  changed_when: true

- name: Set DPDK PMD mask
  command: "ovs-vsctl --no-wait set Open_vSwitch . \
            other_config:pmd-cpu-mask='{{ ovs_dpdk_pmd_mask.stdout_lines[0] }}'"
  changed_when: true

- name: Get number of NUMA nodes defined
  set_fact:
    no_numa_def: "{{ host_description['numa_nodes'].keys() | length | int }}"

- name: Generate total socket memory string for dpdk
  set_fact:
    ovs_dpdk_socket_mem_mb: "{{ ovs_dpdk_socket_mem_mb | default('') | string +
                                ',' + host_description['numa_nodes'][item]
                                ['dpdk_socket_mem'] | string }}"
  loop: "{{ range(0, (no_numa_def | int )) | list }}"

- name: Set DPDK socket memory
  command: "ovs-vsctl --no-wait set Open_vSwitch . \
            other_config:dpdk-socket-mem='{{ ovs_dpdk_socket_mem_mb[1:] }}'"
  changed_when: true

- name: Enable DPDK support for Open vSwitch
  command: "ovs-vsctl --no-wait set Open_vSwitch . other_config:dpdk-init=true"
  changed_when: true

- name: Restart Open vSwitch to apply changes
  systemd:
    name: "{{ ovs_service_name }}"
    state: restarted
    enabled: yes

- name: Pause for 5 seconds to ensure services have time to come back up
  pause:
    seconds: 5

- name: Create vhost_socket directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "libvirt-qemu"
    group: "{{ vhost_socket_directory_group }}"
    mode: "0755"
  with_items:
    - "/var/lib/vhost_socket"
  when: vhost_socket_directory_group is defined

- name: Get bridge name
  set_fact:
    ovs_bridge_name: "{{ item.key }}"
  loop: "{{ host_description['bridge_mappings'] | dict2items }}"

- name: Setup network provider bridges
  openvswitch_bridge:
    bridge: "{{ ovs_bridge_name }}"
    set: "bridge {{ ovs_bridge_name }} datapath_type='{{ ovs_datapath }}'"
    fail_mode: secure
    state: present

- name: Get list of interface name(s) to be binded to the OVS bridge
  set_fact:
    bridge_int_names: "{{ host_description['bridge_mappings'][ovs_bridge_name] }}"

- name: Get interface's pci address
  set_fact:
    "{{ item[0] }}_pci_addr": "{{ item[1]['interfaces'][item.0].pci_address }}"
  loop: "{{ bridge_int_names | product(host_description['numa_nodes'].values()) | list }}"
  when: item[1].interfaces is defined and item[0] in item[1]['interfaces']

- name: Add ports to network provider bridges
  openvswitch_port:
    bridge: "{{ ovs_bridge_name }}"
    port: "{{ int_name }}"
    set: "Interface {{ int_name }} type={{ ovs_dpdk_interface_type }} \
          options:dpdk-devargs='{{ lookup('vars',int_name + '_pci_addr') }}'"
    state: present
  loop: "{{ host_description['bridge_mappings'].values() | list | flatten(levels=1) }}"
  loop_control:
    loop_var: int_name
