# Copyright (c) 2019 Intel Corporation. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


---
- name: Verify nova_conf_path
  fail:
    msg: Ensure nova_conf_path is defined and a string
  when: nova_conf_path is not defined or
        nova_conf_path is not string

- name: Verify cpu_allocation_ratio
  fail:
    msg: cpu_allocation_ratio is not defined or not a float or not an integer
  when: cpu_allocation_ratio is not defined or not
        (cpu_allocation_ratio | type_debug == 'int' or
        cpu_allocation_ratio | type_debug == 'float')

- name: Verify restart_nova
  fail:
    msg: restart_nova is not defined or is not a boolean
  when: restart_nova is not defined or not
        restart_nova | type_debug == 'bool'

- name: Verify nova_service_name
  fail:
    msg: Ensure nova_service_name is defined and a string
  when: nova_service_name is not defined or
        nova_service_name is not string

- name: Verify OpenStack username & password are defined
  fail:
    msg: Please specify Ansible variables OS_USERNAME & OS_PASSWORD
  when: OS_USERNAME is undefined or
        OS_PASSWORD is undefined

- name: Verify OpenStack Ansible variables are defined
  fail:
    msg: >
      Please specify Ansible variables OS_AUTH_URL, OS_REGION_NAME,
      OS_PROJECT_NAME, OS_USER_DOMAIN_ID and OS_PLACEMENT_API_VERSION
  when: OS_AUTH_URL is undefined or
        OS_REGION_NAME is undefined or
        OS_PROJECT_NAME is undefined or
        OS_USER_DOMAIN_ID is undefined or
        OS_PLACEMENT_API_VERSION is undefined
