---
- name: Gather information about secrets file
  delegate_to: localhost
  stat:
    path: "{{ secrets_path }}"
  register: secrets_st

- name: Check if secrets file exists
  fail:
    msg: "Secrets file does not exist at path '{{ secrets_path }}'"
  when: not secrets_st.stat.exists

- name: Check if secrets file has correct file permissions
  fail:
    msg: "Secrets file permissions is not set to mode '0640'"
  when: secrets_st.stat.mode != "0640"

- name: Consume secrets file key - value pairs
  include_vars:
    file: "{{ secrets_path }}"
